[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "mlb_sentiment"
version = "0.1.0"
description = "Quantifying MLB fanbase sentiments from in-game events."
readme = "README.md"
requires-python = ">=3.8.10"
license = { file = "LICENSE" }
dependencies = [
    "praw>=7.8.1",
    "python-dotenv>=1.0.1",
    "requests>=2.32.4",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.0.0",
    "black>=24.0.0",
    "flake8>=7.0.0",
    "mypy>=1.0.0",
]

[tool.setuptools.packages.find]
where = ["src"]