[server]
enableStaticServing = true

[theme]
primaryColor = "#80ADF6"
backgroundColor = "#EBEEF0"
secondaryBackgroundColor = "#F2F3F4"
textColor = "#3d3a2a"
linkColor = "#3d3a2a"
borderColor = "#DADADA"
showWidgetBorder = true
baseRadius = "0.6rem"
font = "Styrene B"
codeFont = "Fira Code:https://fonts.googleapis.com/css2?family=Fira+Code:wght@300..700&display=swap"
codeBackgroundColor = "#ecebe4"
showSidebarBorder = true
headingFontSizes = ["40px", "32px", "24px"]
headingFontWeights = 500


[theme.sidebar]
backgroundColor = "#D4D6D8"
secondaryBackgroundColor = "#F2F3F4"


[[theme.fontFaces]]
url = "app/static/Styrene_B_Family/StyreneB-Thin-Trial.otf"
family = "Styrene B"
weight = 100

[[theme.fontFaces]]
url = "app/static/Styrene_B_Family/StyreneB-Light-Trial.otf"
family = "Styrene B"
weight = 300

[[theme.fontFaces]]
url = "app/static/Styrene_B_Family/StyreneB-Regular-Trial.otf"
family = "Styrene B"
weight = 400

[[theme.fontFaces]]
url = "app/static/Styrene_B_Family/StyreneB-Medium-Trial.otf"
family = "Styrene B"
weight = 500

[[theme.fontFaces]]
url = "app/static/Styrene_B_Family/StyreneB-Bold-Trial.otf"
family = "Styrene B"
weight = 700

[[theme.fontFaces]]
url = "app/static/Styrene_B_Family/StyreneB-Black-Trial.otf"
family = "Styrene B"
weight = 900